#!/usr/bin/env bash
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$HERE/_lib.sh"

LI_ENV="$ENV_DIR/catalyrst-lists.env"

log "loading db credentials"
load_db_creds

if ! grep -q '^POSTGRES_PE_USER=' "$ENV_DIR/db.env"; then
  warn "places_events credentials not in env/db.env — run scripts/bootstrap-places-events.sh first"
  exit 1
fi
if ! grep -q '^POSTGRES_PLACES_API_USER=' "$ENV_DIR/db.env"; then
  warn "catalyrst-places reader role missing — run scripts/bootstrap-catalyrst-places.sh first"
  exit 1
fi
set -a; source "$ENV_DIR/db.env"; set +a

if ! pg_isready -h "$PG_HOST" -p "$PG_PORT" -U "$POSTGRES_USER" >/dev/null 2>&1; then
  warn "postgres not running on $PG_HOST:$PG_PORT — start the database stack first."
  exit 1
fi

log "creating lists_* tables + granting SELECT to $POSTGRES_PLACES_API_USER"
PGPASSWORD="$POSTGRES_PE_PASSWORD" psql -h "$PG_SOCK_DIR" -p "$PG_PORT" \
  -U "$POSTGRES_PE_USER" -d "$POSTGRES_PE_DB" -v ON_ERROR_STOP=1 --no-psqlrc <<SQL
CREATE TABLE IF NOT EXISTS lists_poi (
    coord       TEXT PRIMARY KEY,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS lists_banned_name (
    name        TEXT PRIMARY KEY,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
GRANT USAGE  ON SCHEMA public TO "$POSTGRES_PLACES_API_USER";
GRANT SELECT ON lists_poi, lists_banned_name TO "$POSTGRES_PLACES_API_USER";
SQL

log "writing $LI_ENV"
DB_URL="postgresql:///$POSTGRES_PE_DB?host=$PG_SOCK_DIR&port=$PG_PORT&user=$POSTGRES_PLACES_API_USER&password=$POSTGRES_PLACES_API_PASSWORD"
cat > "$LI_ENV" <<EOF
# auto-generated by scripts/bootstrap-catalyrst-lists.sh — do not commit

HTTP_SERVER_HOST=<HOST>
HTTP_SERVER_PORT=5143

PLACES_PG_COMPONENT_PSQL_CONNECTION_STRING="$DB_URL"

RUST_LOG=catalyrst_lists=info,tower_http=info
EOF
chmod 600 "$LI_ENV"

log "seeding lists from live upstream"
"$HERE/sync-lists.sh" || warn "initial seed failed; lists-daily.timer will retry"

log "bootstrap-catalyrst-lists complete."
log "  next:  nix run .#install-units && systemctl --user enable --now catalyrst-lists.service"
