import {useEffect,useRef,useState} from 'react';
import {Dialog} from './Dialog';
import {execute,type Opened,type WalletIdentity} from './api';
export function ChannelSettings({opened,identity,onClose,onSaved}:{opened:Opened;identity:WalletIdentity;onClose:()=>void;onSaved:()=>void}){
 const channel=opened.channel||'general',config=opened.channelConfig;
 const [privateChannel,setPrivate]=useState(config?.private||false),[members,setMembers]=useState(config?.members.join('\n')||''),[readOnly,setReadOnly]=useState(config?.read_only||false),[slowMode,setSlowMode]=useState(config?.slow_mode||0),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const active=useRef(true);useEffect(()=>()=>{active.current=false;},[]);
 return <Dialog title="Channel settings" onClose={onClose}><form className="dialog-content community-editor" onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{await execute(identity,{type:'configure_channel',community_id:opened.community.id,channel,config:{private:privateChannel,members:members.split(/[\s,]+/).filter(Boolean),read_only:readOnly,slow_mode:slowMode}},()=>active.current);if(active.current)onSaved();}catch(e){if(active.current)setError(e instanceof Error?e.message:'Could not save channel.');}finally{if(active.current)setBusy(false);}}}><h2>#{channel}</h2>{channel!=='general'&&<label className="preference-row"><span>Private channel</span><input type="checkbox" checked={privateChannel} onChange={e=>setPrivate(e.target.checked)}/></label>}{privateChannel&&<label>Invited member wallets<textarea aria-label="Invited member wallets" value={members} onChange={e=>setMembers(e.target.value)} placeholder="0x&#x2026;"/><small>One wallet per line. Owners and moderators always have access.</small></label>}<label className="preference-row"><span>Only moderators can post</span><input type="checkbox" checked={readOnly} onChange={e=>setReadOnly(e.target.checked)}/></label><label>Slow mode<select aria-label="Slow mode" value={slowMode} onChange={e=>setSlowMode(Number(e.target.value))}><option value={0}>Off</option>{[5,10,30,60,300,3600].map(n=><option key={n} value={n}>{n<60?`${n} seconds`:`${n/60} minutes`}</option>)}</select></label>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy?'Saving\u2026':'Save channel'}</button></form></Dialog>;
}
