import { useEffect, useRef, useState, type ReactNode } from 'react';
import type { SocialSettings as Settings } from '@dcl/protocol/out-js/decentraland/social_service/v2/social_service_v2.gen';
import { Dialog } from './Dialog';
import { audioPreferences, saveAudioPreferences } from './audioPreferences';
import './voice-settings.css';

export function SocialSettings({tab: initialTab, onClose, load, save, device, general}: {
  general: ReactNode; tab:'general'|'privacy'|'audio'; onClose:()=>void; load:()=>Promise<Settings>; save:(settings:Settings)=>Promise<Settings>;
  device:(kind:'audioinput'|'audiooutput',id:string)=>Promise<void>;
}) {
  const [tab,setTab] = useState(initialTab);
  const [settings,setSettings] = useState<Settings>();
  const [busy,setBusy] = useState(false);
  const [error,setError] = useState('');
  const [saved,setSaved] = useState(false);
  const [retry,setRetry] = useState(0);
  useEffect(() => { let current=true;setError(''); void load().then(value=>{if(current)setSettings(value);}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;}; }, [load,retry]);
  async function submit() {
    if(!settings||busy)return; setBusy(true);setError('');setSaved(false);
    try { setSettings(await save(settings));setSaved(true); } catch(e){setError(e instanceof Error?e.message:'Could not save settings.');} finally{setBusy(false);}
  }
  return <Dialog title="Preferences" onClose={onClose}><div className="dialog-content social-settings"><h2>Preferences</h2><nav className="inbox-tabs" aria-label="Settings sections"><button aria-pressed={tab==='general'} onClick={()=>setTab('general')}>General</button><button aria-pressed={tab==='privacy'} onClick={()=>setTab('privacy')}>Privacy</button><button aria-pressed={tab==='audio'} onClick={()=>setTab('audio')}>Audio</button></nav>{tab==='general'?general:tab==='audio'?<AudioSettings device={device}/>:<><p className="muted">Decentraland settings travel with your wallet.</p>{settings?<form onSubmit={e=>{e.preventDefault();void submit();}}><label>Who can send you private messages?<select value={settings.privateMessagesPrivacy} onChange={e=>{setSettings({...settings,privateMessagesPrivacy:Number(e.target.value)});setSaved(false);}}><option value={1}>Friends only</option><option value={0}>Everyone</option></select></label><small>dcl.social currently supports conversations with friends. Explorer also uses this privacy setting.</small><label>Blocked people's public messages<select value={settings.blockedUsersMessagesVisibility} onChange={e=>{setSettings({...settings,blockedUsersMessagesVisibility:Number(e.target.value)});setSaved(false);}}><option value={1}>Hide in Explorer</option><option value={0}>Show in Explorer</option></select></label><label>Situation reactions<select value={settings.showSituationReactions} onChange={e=>{setSettings({...settings,showSituationReactions:Number(e.target.value)});setSaved(false);}}><option value={0}>Show in Explorer</option><option value={1}>Hide in Explorer</option></select></label><button className="primary" disabled={busy}>{busy?'Saving\u2026':'Save privacy'}</button>{saved&&<span role="status">Saved</span>}</form>:!error&&<p>Loading privacy settings&#x2026;</p>}<LocalPrivacy /></>}{error&&tab==='privacy'&&<div role="alert"><p>{error}</p>{!settings&&<button className="outline-button" onClick={()=>setRetry(n=>n+1)}>Retry privacy settings</button>}</div>}</div></Dialog>;
}
function LocalPrivacy(){const [calls,setCalls]=useState(()=>audioPreferences().incomingCalls);return <div className="local-privacy"><h3>On this browser</h3><label className="settings-switch"><input type="checkbox" checked={calls} onChange={e=>{setCalls(e.target.checked);saveAudioPreferences({incomingCalls:e.target.checked});}}/>Allow incoming friend calls</label><small>When off, dcl.social declines new calls. This does not change your Explorer presence or location.</small></div>;}
function AudioSettings({device}:{device:(kind:'audioinput'|'audiooutput',id:string)=>Promise<void>}) {
  const [preferences,setPreferences]=useState(audioPreferences);
  const [devices,setDevices]=useState<MediaDeviceInfo[]>([]);
  const [testing,setTesting]=useState(false);
  const [testPending,setTestPending]=useState(false);
  const [level,setLevel]=useState(0);
  const [error,setError]=useState('');
  const [busy,setBusy]=useState(false);
  const mounted=useRef(true), stream=useRef<MediaStream|null>(null), context=useRef<AudioContext|null>(null), frame=useRef(0), generation=useRef(0);
  const stop=()=>{generation.current++;cancelAnimationFrame(frame.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;void context.current?.close();context.current=null;if(mounted.current){setTesting(false);setTestPending(false);setLevel(0);}};
  useEffect(()=>{mounted.current=true;const preferencesChanged=()=>setPreferences(audioPreferences());window.addEventListener('social:audio-preferences',preferencesChanged);const refresh=()=>{void navigator.mediaDevices?.enumerateDevices().then(values=>{if(mounted.current)setDevices(values);}).catch(()=>{if(mounted.current)setError('Audio devices could not be listed.');});};refresh();navigator.mediaDevices?.addEventListener('devicechange',refresh);return()=>{mounted.current=false;stop();window.removeEventListener('social:audio-preferences',preferencesChanged);navigator.mediaDevices?.removeEventListener('devicechange',refresh);};},[]);
  async function choose(kind:'audioinput'|'audiooutput',id:string){setBusy(true);setError('');if(kind==='audioinput')stop();try{await device(kind,id);const patch=kind==='audioinput'?{input:id}:{output:id};saveAudioPreferences(patch);setPreferences(audioPreferences());}catch(e){setError(e instanceof Error?e.message:'Could not switch audio device.');}finally{setBusy(false);}}
  async function test(){if(testing||testPending){stop();return;}stop();const current=generation.current;setError('');setTestPending(true);try{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone testing requires a supported browser and HTTPS.');const media=await navigator.mediaDevices.getUserMedia({audio:{deviceId:preferences.input==='default'?undefined:{exact:preferences.input}},video:false});if(!mounted.current||current!==generation.current){media.getTracks().forEach(t=>t.stop());return;}stream.current=media;const ctx=new AudioContext();context.current=ctx;const analyser=ctx.createAnalyser();analyser.fftSize=256;ctx.createMediaStreamSource(media).connect(analyser);await ctx.resume();if(!mounted.current||current!==generation.current)return;setTestPending(false);setTesting(true);setDevices(await navigator.mediaDevices.enumerateDevices());const samples=new Uint8Array(analyser.fftSize);const tick=()=>{if(!mounted.current||current!==generation.current)return;analyser.getByteTimeDomainData(samples);const rms=Math.sqrt(samples.reduce((sum,v)=>sum+(v-128)**2,0)/samples.length)/128;setLevel(Math.min(100,rms*350));frame.current=requestAnimationFrame(tick);};tick();}catch(e){stop();if(mounted.current)setError(e instanceof Error?e.message:'Microphone is unavailable.');}}
  const options=(kind:MediaDeviceKind)=>devices.filter(d=>d.kind===kind&&d.deviceId&&d.deviceId!=='default');
  return <div className="audio-settings"><p className="muted">Choose the devices for your current call or your next one. These preferences stay on this browser. You always join muted.</p><label>Microphone<select aria-label="Microphone device" disabled={busy} value={preferences.input} onChange={e=>void choose('audioinput',e.target.value)}><option value="default">System default</option>{preferences.input!=='default'&&!options('audioinput').some(d=>d.deviceId===preferences.input)&&<option value={preferences.input}>Saved microphone unavailable</option>}{options('audioinput').map((d,i)=><option value={d.deviceId} key={d.deviceId}>{d.label||`Microphone ${i+1}`}</option>)}</select></label><label>Speakers<select aria-label="Speaker device" disabled={busy||!('setSinkId' in HTMLMediaElement.prototype)} value={preferences.output} onChange={e=>void choose('audiooutput',e.target.value)}><option value="default">System default</option>{preferences.output!=='default'&&!options('audiooutput').some(d=>d.deviceId===preferences.output)&&<option value={preferences.output}>Saved speakers unavailable</option>}{options('audiooutput').map((d,i)=><option value={d.deviceId} key={d.deviceId}>{d.label||`Speakers ${i+1}`}</option>)}</select></label>{!('setSinkId' in HTMLMediaElement.prototype)&&<small>This browser uses your system's speaker selection.</small>}<label>Voice volume <output>{preferences.volume}%</output><input aria-label="Voice volume" type="range" min="0" max="100" value={preferences.volume} onChange={e=>{const volume=Number(e.target.value);saveAudioPreferences({volume});setPreferences({...preferences,volume});}}/></label><div className="mic-test"><button className="outline-button" onClick={()=>void test()}>{testPending?'Cancel microphone test':testing?'Stop microphone test':'Test microphone'}</button><meter aria-label="Microphone input level" min="0" max="100" value={level}/><small>{testing?'Testing locally. Your microphone is not sent to anyone.':'A test asks for microphone permission and makes device names available.'}</small></div>{error&&<p role="alert">{error}</p>}</div>;
}
