import { Avatar, Name } from './Profile';
import { type VoiceState, type VoiceModeration } from './voice';
import './voice-settings.css';
export function Voice({state,community,self,canStart,join,leave,mute,deafen,hand,moderate,localMute}: {state:VoiceState;community:string;self:string;canStart:boolean;join:(start?:boolean)=>void;leave:()=>void;mute:()=>void;deafen:()=>void;hand:()=>void;moderate:(action:VoiceModeration,address?:string)=>void;localMute:(address:string)=>void}) {
  const here = state.community === community;
  const host = here && state.connected && state.host;
  const requests = state.participants.filter(p=>p.raised&&!p.speaker);
  return <section className="voice-stage" aria-label="Community voice"><div className="voice-copy"><small className="voice-badge">{here && state.connected ? `${state.participants.length} hanging out` : 'The lounge'}</small><h1>A familiar place to land.</h1><p>Drop in. Say hello. Stay a while.</p></div>
    {host&&requests.length>0&&<section className="voice-requests" aria-label="Requests to speak"><h2>Hands up &#xb7; {requests.length}</h2>{requests.map(p=><div className="voice-request" key={p.wallet}><Avatar wallet={p.wallet}/><strong><Name wallet={p.wallet}/></strong><button className="primary" disabled={state.moderating} onClick={()=>moderate('promote',p.wallet)}>Let speak</button><button className="outline-button" disabled={state.moderating} onClick={()=>moderate('reject',p.wallet)}>Decline</button></div>)}</section>}
    {here && state.participants.length > 0 && <div className="voice-people">{state.participants.map(p => <div className={`voice-tile ${p.speaking ? 'speaking' : ''}`} key={p.wallet}><Avatar wallet={p.wallet} /><strong><Name wallet={p.wallet} /></strong><div className="voice-person-status">{p.role==='owner'||p.role==='moderator'?'Host':p.speaker?'Speaker':'Listening'}{p.raised?' \u00b7 Hand raised':p.speaker&&p.muted?' \u00b7 Muted':''}</div>{p.wallet.toLowerCase()!==self.toLowerCase()&&<button className="outline-button" onClick={()=>localMute(p.wallet)}>{p.localMuted?'Unmute for me':'Mute for me'}</button>}{host&&p.wallet.toLowerCase()!==self.toLowerCase()&&<div className="voice-tile-controls"><button disabled={state.moderating} onClick={()=>moderate(p.speaker?'demote':'promote',p.wallet)}>{p.speaker?'Move to listeners':'Make speaker'}</button>{p.speaker&&<button disabled={state.moderating} onClick={()=>moderate(p.hostMuted?'unmute':'mute',p.wallet)}>{p.hostMuted?'Allow unmute':'Mute speaker'}</button>}<button className="voice-danger" disabled={state.moderating} onClick={()=>moderate('kick',p.wallet)}>Remove from voice</button></div>}</div>)}</div>}
    {here && state.connected ? <div className="voice-controls">{state.canSpeak ? <button className="outline-button" disabled={state.hostMuted} aria-pressed={!state.muted} onClick={mute}>{state.hostMuted?'Muted by host':state.muted ? 'Unmute' : 'Mute'}</button> : <button className="outline-button" aria-pressed={state.raised} onClick={hand}>{state.raised ? 'Lower hand' : 'Raise hand'}</button>}<button className="outline-button" aria-pressed={state.deafened} onClick={deafen}>{state.deafened ? 'Sound on' : 'Deafen'}</button><button className="outline-button" onClick={()=>window.dispatchEvent(new CustomEvent('social:settings',{detail:'audio'}))}>Audio settings</button><button className="primary" onClick={leave}>Leave voice</button>{host&&<button className="outline-button voice-danger" disabled={state.moderating} onClick={()=>{if(window.confirm('End this voice chat for everyone?'))moderate('end');}}>End for everyone</button>}</div> : <><div className="voice-controls"><button className="primary" disabled={state.busy} onClick={() => join()}>{state.busy ? 'Connecting\u2026' : 'Join voice'}</button>{canStart && <button className="outline-button" disabled={state.busy} onClick={() => join(true)}>Start voice chat</button>}</div><small>You join with your microphone off.</small></>}{here && state.error && <p className="friends-error" role="alert">{state.error}</p>}</section>;
}
