use super::{Group, Svc};

pub(super) const CATALOG: &[Group] = &[
    Group {
        key: "content",
        title: "Content core",
        bundle: "catalyrst-live · :5141",
        multi: false,
        detail: &[
            ("About", "/about"),
            ("Content status", "/content/status"),
            ("Lambdas status", "/lambdas/status"),
        ],
        services: &[
            Svc {
                name: "Content store",
                member: "",
                reference: "catalyst content-server",
                desc: "Content-addressed scenes, wearables, emotes & profiles (ADR-45 / IPFS CIDs)",
                path: "/content/status",
            },
            Svc {
                name: "Lambdas",
                member: "",
                reference: "catalyst lambdas",
                desc: "Profiles, wearable/emote catalogs, LAND & third-party items",
                path: "/lambdas/status",
            },
            Svc {
                name: "About",
                member: "",
                reference: "realm descriptor",
                desc: "Realm identity, comms config & health for explorer clients",
                path: "/about",
            },
        ],
    },
    Group {
        key: "explore",
        title: "Explore",
        bundle: "catalyrst-explore · :5143",
        multi: true,
        detail: &[
            ("Bundle health", "/health"),
            ("Archipelago core", "/core-status"),
            ("Archipelago stats", "/stats/health"),
            ("Hot scenes", "/hot-scenes"),
            ("Comms islands", "/comms/islands"),
            ("Comms parcels", "/comms/parcels"),
        ],
        services: &[
            Svc {
                name: "Places",
                member: "places",
                reference: "places.decentraland.org",
                desc: "Place discovery, favorites & content-moderation reports",
                path: "/places",
            },
            Svc {
                name: "Events",
                member: "events",
                reference: "events.decentraland.org",
                desc: "Event schedules, posters & attendance",
                path: "/events/",
            },
            Svc {
                name: "Map",
                member: "map",
                reference: "atlas-server",
                desc: "Genesis-city tiles, minimap & map.png renderer",
                path: "/v1/map.png",
            },
            Svc {
                name: "Worlds",
                member: "worlds",
                reference: "worlds-content-server",
                desc: "World realms — about, permissions & comms",
                path: "/worlds",
            },
            Svc {
                name: "Archipelago",
                member: "archipelago",
                reference: "archipelago-workers",
                desc: "Peer clustering, ws-connector & hot scenes",
                path: "/hot-scenes",
            },
            Svc {
                name: "Lists",
                member: "lists",
                reference: "dcl-lists",
                desc: "Curated POIs & banned-name denylist",
                path: "/pois",
            },
        ],
    },
    Group {
        key: "create",
        title: "Create",
        bundle: "catalyrst-create · :5144",
        multi: true,
        detail: &[
            ("Bundle health", "/health"),
            ("AB build queues", "/queues/status"),
            ("AB registry status", "/status"),
        ],
        services: &[
            Svc {
                name: "Builder",
                member: "builder",
                reference: "builder-server",
                desc: "Collection items, storage & newsletter",
                path: "",
            },
            Svc {
                name: "Camera Reel",
                member: "camera-reel",
                reference: "camera-reel-service",
                desc: "Content-addressed in-world photo store",
                path: "/images",
            },
            Svc {
                name: "AB Registry",
                member: "ab-registry",
                reference: "asset-bundle-registry",
                desc: "Asset-bundle build status, versions & bundles",
                path: "/registry",
            },
        ],
    },
    Group {
        key: "social",
        title: "Social",
        bundle: "catalyrst-social · :5145",
        multi: true,
        detail: &[("Bundle health", "/health"), ("Comms status", "/status")],
        services: &[
            Svc {
                name: "Communities",
                member: "communities",
                reference: "social-service-ea",
                desc: "Community routes with authority-chain federation",
                path: "",
            },
            Svc {
                name: "Comms Gatekeeper",
                member: "comms",
                reference: "comms-gatekeeper",
                desc: "LiveKit tokens, scene bans, voice & Cast 2.0",
                path: "",
            },
            Svc {
                name: "Notifications",
                member: "notifications",
                reference: "notifications",
                desc: "Signed-fetch notification reader & marker",
                path: "",
            },
            Svc {
                name: "Badges",
                member: "badges",
                reference: "badges",
                desc: "Profile badge state",
                path: "/badges/",
            },
            Svc {
                name: "Autotranslate",
                member: "media",
                reference: "autotranslate-server",
                desc: "LibreTranslate-compatible /translate",
                path: "",
            },
        ],
    },
    Group {
        key: "data",
        title: "Data",
        bundle: "catalyrst-data · :5146",
        multi: true,
        detail: &[("Bundle health", "/health")],
        services: &[
            Svc {
                name: "Marketplace",
                member: "market",
                reference: "marketplace-server",
                desc: "Catalog, items, orders, bids, sales & trades",
                path: "/v1/catalog",
            },
            Svc {
                name: "Transactions",
                member: "economy",
                reference: "transactions-server",
                desc: "Meta-transaction relay",
                path: "",
            },
            Svc {
                name: "Price feed",
                member: "price",
                reference: "coingecko proxy",
                desc: "MANA / token spot prices over the mana_price archive",
                path: "/api/v3/simple/price",
            },
            Svc {
                name: "Credits",
                member: "credits",
                reference: "credits.decentraland.org",
                desc: "Marketplace Credits program API",
                path: "/seasons",
            },
            Svc {
                name: "EVM RPC",
                member: "rpc",
                reference: "rpc.decentraland.org",
                desc: "Method-filtered read-only JSON-RPC relay",
                path: "",
            },
        ],
    },
    Group {
        key: "ab-cdn",
        title: "Asset bundle CDN",
        bundle: "abgen · :5147 (upstream decentraland/abgen)",
        multi: false,
        detail: &[("Health", "/health")],
        services: &[Svc {
            name: "AB CDN",
            member: "",
            reference: "ab-cdn",
            desc: "Content-addressed LODs, manifests & asset-bundle binaries",
            path: "/manifest/",
        }],
    },
    Group {
        key: "social-rpc",
        title: "Social RPC",
        bundle: "catalyrst-social-rpc · :5148",
        multi: false,
        detail: &[("Health", "/health"), ("Info", "/info")],
        services: &[Svc {
            name: "Friends & voice",
            member: "",
            reference: "social-service-ea",
            desc: "dcl-rpc WebSocket — friends, presence, blocks, mutes & voice",
            path: "",
        }],
    },
    Group {
        key: "scene-state",
        title: "Scene state",
        bundle: "catalyrst-scene-state · :5153",
        multi: false,
        detail: &[("Status", "/status")],
        services: &[Svc {
            name: "SDK7 multiplayer",
            member: "",
            reference: "scene-state-server",
            desc: "Authoritative SDK7 scene state (HTTP + WebSocket CRDT)",
            path: "",
        }],
    },
    Group {
        key: "profile-images",
        title: "Profile images",
        bundle: "catalyrst-profile-images · :5154",
        multi: false,
        detail: &[("Health", "/health")],
        services: &[Svc {
            name: "Avatar thumbnails",
            member: "",
            reference: "profile-images",
            desc: "Headless-godot avatar render with disk cache",
            path: "",
        }],
    },
    Group {
        key: "explorer-api",
        title: "Explorer API",
        bundle: "catalyrst-explorer-api · :5137",
        multi: false,
        detail: &[("Health", "/health"), ("Auth health", "/auth/health/live")],
        services: &[
            Svc {
                name: "Realm provider",
                member: "",
                reference: "realm-provider",
                desc: "Realm selection for explorer clients",
                path: "",
            },
            Svc {
                name: "Auth & flags",
                member: "",
                reference: "auth-api · feature-flags",
                desc: "Auth API, blocklist, builder-api & feature flags",
                path: "",
            },
        ],
    },
    Group {
        key: "telemetry",
        title: "Observability",
        bundle: "catalyrst-telemetry",
        multi: false,
        detail: &[("Health", "/health")],
        services: &[
            Svc {
                name: "Telemetry sink",
                member: "",
                reference: "sentry + segment",
                desc: "Client error/analytics ingest stored in Postgres",
                path: "",
            },
            Svc {
                name: "Dashboard",
                member: "",
                reference: "telemetry",
                desc: "Errors, metrics, release health, flags & ad-hoc SQL",
                path: "",
            },
        ],
    },
];
