-- Charge-basis pinning for fulfillment (never charge != pay).
--
-- `basis_wei` records the exact wei amount a line's Credits charge was
-- derived from. For secondary-mode lines this is the price of the specific
-- cheapest open MarketplaceV2 listing selected at checkout (whose tokenId is
-- already in `token_id`); the outbox worker then buys exactly
-- (token_id, basis_wei) — MarketplaceV2.executeOrder binds both on-chain and
-- reverts on any mismatch, so fulfillment can never pay a different amount
-- than the one the buyer was charged for. NULL = primary/mint line or a
-- legacy row from before pinning (the worker falls back to fresh selection,
-- guarded against paying for 0-charged lines).
ALTER TABLE fulfillment_outbox ADD COLUMN IF NOT EXISTS basis_wei TEXT;
