import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { z } from "zod";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const text = z.string().trim().min(20);
export const ProductSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  capabilities: z.array(z.object({
    name: z.string().min(1),
    status: z.enum(["implemented", "partial", "preview", "unavailable"]),
    evidence: z.array(z.string().min(1)).min(1),
  })).min(1),
  assumptions: z.object({
    identity: text, availability: text, persistence: text, completion: text, measurement: text,
  }).strict(),
});

export function auditProducts(base = root) {
  const catalog = z.object({ reviewed: z.string(), products: z.array(ProductSchema) }).parse(
    JSON.parse(fs.readFileSync(path.join(base, "docs/product-capabilities.json"), "utf8")),
  );
  const storyRoot = path.join(base, "packages/features/src/stories");
  const stories = fs.readdirSync(storyRoot, { recursive: true }).map(String).filter((p) => p.endsWith("/story.md"));
  const groups = new Set(stories.map((p) => p.split(path.sep)[0]));
  const ids = catalog.products.map((p) => p.id);
  if (new Set(ids).size !== ids.length) throw new Error("Duplicate product id");
  for (const group of groups) if (!ids.includes(group)) throw new Error(`Missing product: ${group}`);
  for (const product of catalog.products) {
    if (!groups.has(product.id)) throw new Error(`No stories for ${product.id}`);
    for (const capability of product.capabilities) {
      for (const evidence of capability.evidence) {
        if (!fs.statSync(path.resolve(base, evidence)).isFile()) throw new Error(`Missing evidence: ${evidence}`);
      }
    }
  }
  const coverage = catalog.products.map((product) => {
    const rows = stories.filter((p) => p.split(path.sep)[0] === product.id).map((p) => matter(fs.readFileSync(path.join(storyRoot, p), "utf8")).data);
    return {
      product: product.id,
      stories: rows.length,
      hypotheses: rows.filter((s) => s.hypothesis?.statement?.trim() && s.hypothesis?.because?.trim()).length,
      comparisons: rows.filter((s) => s.experiment?.variants?.filter((v: { weight: number }) => v.weight > 0).length > 1).length,
      explicitRates: rows.filter((s) => s.metric?.numerator && s.metric?.denominator).length,
      unassigned: rows.filter((s) => !s.owner || /example\.com|TODO/i.test(s.owner)).length,
    };
  });
  return { ...catalog, coverage };
}

function report(result: ReturnType<typeof auditProducts>) {
  const lines = ["# Product capabilities and assumptions", "", `Code review: ${result.reviewed}. Generated by \`npm run products:audit -- --write\`.`, "",
    "This is a source-wiring audit, not a live deployment certification or a complete inventory of every route. Each product answers the same five questions. Similar rigor does not mean equal feature counts or identical prerequisites.", "",
    "**Statuses:** implemented = a production path exists; partial = prerequisites or sub-actions remain incomplete; preview = simulated/local demonstration; unavailable = refuses the action. An implemented path still depends on authorization and working services.", "",
    "## Story coverage", "", "A hypothesis is an assumption until measured. Multiple positive-weight arms permit a comparison; one arm does not establish lift. Baselines/MDEs are planning inputs unless sourced. Unassigned ownership and implicit rate definitions remain visible rather than being fabricated.", "",
    "| Product | Stories | Hypotheses | Comparison designs | Explicit rate pairs | Unassigned owners |", "| --- | ---: | ---: | ---: | ---: | ---: |"];
  for (const row of result.coverage) lines.push(`| ${row.product} | ${row.stories} | ${row.hypotheses} | ${row.comparisons} | ${row.explicitRates} | ${row.unassigned} |`);
  for (const product of result.products) {
    lines.push("", `## ${product.name}`, "", "### Capabilities", "");
    for (const capability of product.capabilities) {
      const links = capability.evidence.map((p) => `[${path.basename(p)}](../${p})`).join(", ");
      lines.push(`- **${capability.name}: ${capability.status}.** Evidence: ${links}.`);
    }
    lines.push("", "### Assumptions to validate", "");
    for (const [key, value] of Object.entries(product.assumptions)) lines.push(`- **${key[0].toUpperCase() + key.slice(1)}:** ${value}`);
  }
  return lines.join("\n") + "\n";
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = auditProducts();
  const markdown = report(result);
  const output = path.join(root, "docs/product-capabilities.md");
  if (process.argv.includes("--write")) fs.writeFileSync(output, markdown);
  else if (process.argv.includes("--check") && fs.readFileSync(output, "utf8") !== markdown) throw new Error("Product report is stale; run npm run products:audit -- --write");
  console.table(result.coverage);
  console.log(`${result.products.length} products: capability evidence and all five assumption dimensions checked.`);
}
